# Generated by Django 2.2 on 2021-03-24 05:46

from django.db import migrations, models
import django.db.models.deletion
import school_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('blood', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=100)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Sikhs', 'Sikhs'), ('Christiian', 'Christiian')], max_length=100)),
                ('caste', models.CharField(choices=[('ST', 'ST'), ('SC', 'SC'), ('OBC', 'OBC'), ('General', 'General')], max_length=100)),
                ('g_phone1', models.IntegerField()),
                ('g_phone2', models.IntegerField()),
                ('g_name', models.CharField(max_length=100)),
                ('g_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('g_profession', models.CharField(max_length=100)),
                ('g_religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Sikhs', 'Sikhs'), ('Christiian', 'Christiian')], max_length=100)),
                ('g_rel_with_guardion', models.CharField(max_length=100)),
                ('g_caddress', models.TextField(max_length=100)),
                ('g_paddress', models.TextField(max_length=100)),
                ('c_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('c_phone', models.IntegerField()),
                ('c_address', models.TextField(max_length=100)),
                ('acad_class', models.CharField(max_length=100)),
                ('aad_prev_school', models.CharField(max_length=100)),
                ('acad_prev_class', models.CharField(max_length=100)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to=school_app.models.student_im)),
                ('f_phone', models.IntegerField()),
                ('f_name', models.CharField(max_length=100)),
                ('f_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('f_profession', models.CharField(max_length=100)),
                ('m_phone', models.IntegerField()),
                ('m_name', models.CharField(max_length=100)),
                ('m_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('m_profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('url_Facebook', models.URLField(default='')),
                ('image', models.ImageField(upload_to=school_app.models.content_file_name1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Faculties',
                'db_table': 'faculties',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fee_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=10)),
                ('add_fee', models.IntegerField(default=0)),
                ('tution_fee', models.IntegerField(default=0)),
                ('science_fee', models.IntegerField(default=0)),
                ('comp_fee', models.IntegerField(default=0)),
                ('dev_fee', models.IntegerField(default=0)),
                ('smart_fee', models.IntegerField(default=0)),
                ('exam_fee', models.IntegerField(default=0)),
                ('total_fee', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Fee_details',
                'db_table': 'Fee_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fee_detail_quarterly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(max_length=5)),
                ('first_quarter', models.IntegerField(default=0)),
                ('second_quarter', models.IntegerField(default=0)),
                ('third_quarter', models.IntegerField(default=0)),
                ('fourth_quarter', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Fee_details_quarterly',
                'db_table': 'Fee_detail_quarterly',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImgCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Notices',
                'db_table': 'notices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TC_certi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=school_app.models.content_tc)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TC_Certificates',
                'db_table': 'TC',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=school_app.models.content_file_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_app.ImgCategory')),
            ],
            options={
                'verbose_name_plural': 'Pictures',
                'db_table': 'pictures',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
