# Generated by Django 2.2 on 2021-08-16 03:46

from django.db import migrations, models
import school_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indeximage',
            name='image',
            field=models.ImageField(upload_to=school_app.models.content_file_name3),
        ),
    ]
