# Generated by Django 2.2 on 2021-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_form',
            name='serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admission_form',
            name='c_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='admission_form',
            name='f_phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='admission_form',
            name='g_phone1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='admission_form',
            name='g_phone2',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='admission_form',
            name='m_phone',
            field=models.CharField(max_length=12),
        ),
    ]
