# Generated by Django 2.2 on 2021-07-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_disclosure_doccategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Disclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=100)),
            ],
        ),
    ]
